<?php
/*
 * Created on 2005/06/26
 *
 * OLUTシステム構成を定義します。
 * 
 */
define('OLUT_DIR', 'c:/eclipse/workspace/olut/');
define('SMARTY_DIR', 'c:/ntc/Smarty-2.6.9/libs/');

define('OLUT_DSN','pgsql://olut:olut@localhost/olut');
//define('OLUT_DSN','pgsql://olut:olut@192.168.1.82/olut');

define('FPDF_FONTPATH','c:/ntc/fpdf153/font/');
define('OLUT_B4_WIDTH', 257);
define('OLUT_B4_HEIGHT',364);
define('OLUT_A4_WIDTH', 210);
define('OLUT_A4_HEIGHT', 297);
define('OLUT_IMAGE_PATH','c:/eclipse/workspace/olut/image/');  // path to NTC logos.
define('OLUT_SYSTEM_PROFILE','c:/eclipse/workspace/olut/OlutProfile.xml');

?>
